// RunSummary.java  – minimal listing DTO
package com.example.pcb.model;

/**
 * Plain-old immutable DTO that mimics the accessor names autogenerated by a record.
 * (Makes it a drop-in replacement without touching any calling code.)
 */
public final class RunSummary {
    private final long   id;
    private final String pcbType;
    private final int    qty;
    private final int    produced;
    private final int    failed;
    private final String ts;        // timestamp

    public RunSummary(long id, String pcbType, int qty,
                      int produced, int failed, String ts) {
        this.id       = id;
        this.pcbType  = pcbType;
        this.qty      = qty;
        this.produced = produced;
        this.failed   = failed;
        this.ts       = ts;
    }

    /* — accessor methods with the same “record-style” names — */
    public long   id()       { return id; }
    public String pcbType()  { return pcbType; }
    public int    qty()      { return qty; }
    public int    produced() { return produced; }
    public int    failed()   { return failed; }
    public String ts()       { return ts; }
}
